name: Close All Issues

on:
  workflow_dispatch: # Allows the workflow to be triggered manually

permissions: 
  issues: write # Explicitly grant write permission to issues

jobs:
  close_issues:
    runs-on: ubuntu-latest

    steps:
      - name: Debug Context
        uses: actions/github-script@v6
        with:
          script: |
            console.log(`Repository: ${context.repo.owner}/${context.repo.repo}`);
            console.log(`Workflow triggered by: ${context.actor}`);

      - name: Fetch and close all open issues
        uses: actions/github-script@v6
        with:
          script: |
            const issues = await github.paginate(github.rest.issues.listForRepo, {
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open' // Fetch only open issues
            });

            if (issues.length === 0) {
              console.log("No open issues to close.");
            } else {
              console.log(`Found ${issues.length} open issues.`);
            }

            for (const issue of issues) {
              if (!issue.pull_request) { // Ensure it’s an issue, not a pull request
                await github.rest.issues.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  state: 'closed'
                });
                console.log(`Closed issue #${issue.number}: ${issue.title}`);
              } else {
                console.log(`Skipped pull request #${issue.number}`);
              }
            }
